# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Receiver.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1078, 986)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(13, 13, 13, 13)
        self.gridLayout.setSpacing(9)
        self.gridLayout.setObjectName("gridLayout")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, -629, 1211, 1529))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_2)
        self.gridLayout_2.setContentsMargins(13, 13, 13, 13)
        self.gridLayout_2.setSpacing(9)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_12 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_12.setObjectName("label_12")
        self.gridLayout_2.addWidget(self.label_12, 30, 7, 1, 1)
        self.out_device_ip = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents_2)
        self.out_device_ip.setMinimumSize(QtCore.QSize(0, 32))
        self.out_device_ip.setSizeIncrement(QtCore.QSize(0, 32))
        self.out_device_ip.setStyleSheet("background-color: rgb(233, 233, 233);")
        self.out_device_ip.setObjectName("out_device_ip")
        self.gridLayout_2.addWidget(self.out_device_ip, 33, 0, 1, 1)
        self.pB_save_pub_key = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.pB_save_pub_key.setObjectName("pB_save_pub_key")
        self.gridLayout_2.addWidget(self.pB_save_pub_key, 40, 7, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 39, 7, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 14, 0, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_15.setObjectName("label_15")
        self.gridLayout_2.addWidget(self.label_15, 31, 0, 1, 1)
        self.pB_start_auto = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.pB_start_auto.setObjectName("pB_start_auto")
        self.gridLayout_2.addWidget(self.pB_start_auto, 6, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 28, 0, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_14.setObjectName("label_14")
        self.gridLayout_2.addWidget(self.label_14, 32, 0, 1, 1)
        self.out_data_zone = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents_2)
        self.out_data_zone.setMinimumSize(QtCore.QSize(0, 32))
        self.out_data_zone.setMaximumSize(QtCore.QSize(16777215, 30))
        self.out_data_zone.setStyleSheet("background-color: rgb(233, 233, 233);")
        self.out_data_zone.setObjectName("out_data_zone")
        self.gridLayout_2.addWidget(self.out_data_zone, 23, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_13.setObjectName("label_13")
        self.gridLayout_2.addWidget(self.label_13, 34, 0, 1, 1)
        self.out_serial_number = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents_2)
        self.out_serial_number.setMinimumSize(QtCore.QSize(0, 32))
        self.out_serial_number.setMaximumSize(QtCore.QSize(16777215, 32))
        self.out_serial_number.setStyleSheet("background-color: rgb(233, 233, 233);")
        self.out_serial_number.setObjectName("out_serial_number")
        self.gridLayout_2.addWidget(self.out_serial_number, 18, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 19, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 21, 0, 1, 1)
        self.out_pic_time = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        self.out_pic_time.setMinimumSize(QtCore.QSize(250, 30))
        self.out_pic_time.setStyleSheet("background-color: rgb(233, 233, 233);")
        self.out_pic_time.setObjectName("out_pic_time")
        self.gridLayout_2.addWidget(self.out_pic_time, 18, 10, 1, 1)
        self.out_conf_zone = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents_2)
        self.out_conf_zone.setMinimumSize(QtCore.QSize(0, 32))
        self.out_conf_zone.setMaximumSize(QtCore.QSize(16777215, 32))
        self.out_conf_zone.setStyleSheet("background-color: rgb(233, 233, 233);")
        self.out_conf_zone.setObjectName("out_conf_zone")
        self.gridLayout_2.addWidget(self.out_conf_zone, 20, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 18, 7, 1, 1)
        self.out_signature = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents_2)
        self.out_signature.setMinimumSize(QtCore.QSize(0, 124))
        self.out_signature.setStyleSheet("background-color: rgb(233, 233, 233);")
        self.out_signature.setObjectName("out_signature")
        self.gridLayout_2.addWidget(self.out_signature, 35, 8, 4, 3)
        self.label_5 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 18, 9, 1, 1)
        self.out_pic_date = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        self.out_pic_date.setMinimumSize(QtCore.QSize(250, 30))
        self.out_pic_date.setStyleSheet("background-color: rgb(233, 233, 233);")
        self.out_pic_date.setObjectName("out_pic_date")
        self.gridLayout_2.addWidget(self.out_pic_date, 18, 8, 1, 1)
        self.display = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.display.setMinimumSize(QtCore.QSize(721, 521))
        self.display.setMaximumSize(QtCore.QSize(1500, 700))
        self.display.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.display.setLineWidth(3)
        self.display.setMidLineWidth(3)
        self.display.setObjectName("display")
        self.gridLayout_2.addWidget(self.display, 0, 7, 5, 5)
        self.pB_save_current_pic = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.pB_save_current_pic.setObjectName("pB_save_current_pic")
        self.gridLayout_2.addWidget(self.pB_save_current_pic, 6, 7, 1, 1)
        self.label = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 6, 8, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_20.setObjectName("label_20")
        self.gridLayout_2.addWidget(self.label_20, 36, 0, 1, 1)
        self.out_hash_value = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents_2)
        self.out_hash_value.setMinimumSize(QtCore.QSize(0, 124))
        self.out_hash_value.setStyleSheet("background-color: rgb(233, 233, 233);")
        self.out_hash_value.setObjectName("out_hash_value")
        self.gridLayout_2.addWidget(self.out_hash_value, 31, 8, 4, 3)
        self.logo = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.logo.setMinimumSize(QtCore.QSize(318, 303))
        self.logo.setMaximumSize(QtCore.QSize(1000000, 10000000))
        self.logo.setObjectName("logo")
        self.gridLayout_2.addWidget(self.logo, 0, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(100, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem1, 18, 6, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_19.setObjectName("label_19")
        self.gridLayout_2.addWidget(self.label_19, 14, 7, 2, 2)
        self.out_public_key = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents_2)
        self.out_public_key.setMinimumSize(QtCore.QSize(0, 124))
        self.out_public_key.setStyleSheet("background-color: rgb(233, 233, 233);")
        self.out_public_key.setObjectName("out_public_key")
        self.gridLayout_2.addWidget(self.out_public_key, 39, 8, 4, 3)
        spacerItem2 = QtWidgets.QSpacerItem(40, 40, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 13, 0, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_18.setObjectName("label_18")
        self.gridLayout_2.addWidget(self.label_18, 4, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 35, 7, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 31, 7, 1, 1)
        self.widget = QtWidgets.QWidget(self.scrollAreaWidgetContents_2)
        self.widget.setObjectName("widget")
        self.gridLayout_2.addWidget(self.widget, 23, 6, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 50, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem3, 27, 7, 3, 3)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem4, 7, 7, 2, 1)
        self.label_sensor_4 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_sensor_4.setObjectName("label_sensor_4")
        self.gridLayout_2.addWidget(self.label_sensor_4, 21, 9, 1, 1)
        self.label_sensor_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_sensor_3.setObjectName("label_sensor_3")
        self.gridLayout_2.addWidget(self.label_sensor_3, 21, 7, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 19, 7, 1, 1)
        self.out_current_counter = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        self.out_current_counter.setMinimumSize(QtCore.QSize(250, 30))
        self.out_current_counter.setStyleSheet("background-color: rgb(233, 233, 233);")
        self.out_current_counter.setObjectName("out_current_counter")
        self.gridLayout_2.addWidget(self.out_current_counter, 19, 8, 1, 1)
        self.label_sensor_1 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_sensor_1.setObjectName("label_sensor_1")
        self.gridLayout_2.addWidget(self.label_sensor_1, 20, 7, 1, 1)
        self.out_sensor_1 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        self.out_sensor_1.setMinimumSize(QtCore.QSize(250, 30))
        self.out_sensor_1.setStyleSheet("background-color: rgb(233, 233, 233);")
        self.out_sensor_1.setObjectName("out_sensor_1")
        self.gridLayout_2.addWidget(self.out_sensor_1, 20, 8, 1, 1)
        self.out_sensor_3 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        self.out_sensor_3.setMinimumSize(QtCore.QSize(250, 30))
        self.out_sensor_3.setStyleSheet("background-color: rgb(233, 233, 233);")
        self.out_sensor_3.setObjectName("out_sensor_3")
        self.gridLayout_2.addWidget(self.out_sensor_3, 21, 8, 1, 1)
        self.out_sensor_2 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        self.out_sensor_2.setMinimumSize(QtCore.QSize(250, 30))
        self.out_sensor_2.setStyleSheet("background-color: rgb(233, 233, 233);")
        self.out_sensor_2.setObjectName("out_sensor_2")
        self.gridLayout_2.addWidget(self.out_sensor_2, 20, 10, 1, 1)
        self.out_sensor_4 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        self.out_sensor_4.setMinimumSize(QtCore.QSize(250, 30))
        self.out_sensor_4.setStyleSheet("background-color: rgb(233, 233, 233);")
        self.out_sensor_4.setObjectName("out_sensor_4")
        self.gridLayout_2.addWidget(self.out_sensor_4, 21, 10, 1, 1)
        self.label_sensor_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_sensor_2.setObjectName("label_sensor_2")
        self.gridLayout_2.addWidget(self.label_sensor_2, 20, 9, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_21.setObjectName("label_21")
        self.gridLayout_2.addWidget(self.label_21, 9, 0, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_17.setObjectName("label_17")
        self.gridLayout_2.addWidget(self.label_17, 1, 0, 1, 1)
        self.out_current_date_time = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents_2)
        self.out_current_date_time.setMinimumSize(QtCore.QSize(250, 32))
        self.out_current_date_time.setMaximumSize(QtCore.QSize(16777215, 30))
        self.out_current_date_time.setStyleSheet("background-color: rgb(233, 233, 233);")
        self.out_current_date_time.setObjectName("out_current_date_time")
        self.gridLayout_2.addWidget(self.out_current_date_time, 2, 0, 1, 1)
        self.in_device_port_pic = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        self.in_device_port_pic.setMinimumSize(QtCore.QSize(0, 32))
        self.in_device_port_pic.setStyleSheet("background-color: rgb(233, 233, 233);")
        self.in_device_port_pic.setObjectName("in_device_port_pic")
        self.gridLayout_2.addWidget(self.in_device_port_pic, 35, 0, 1, 1)
        self.in_device_port_pubkey = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        self.in_device_port_pubkey.setMinimumSize(QtCore.QSize(0, 32))
        self.in_device_port_pubkey.setStyleSheet("background-color: rgb(233, 233, 233);")
        self.in_device_port_pubkey.setObjectName("in_device_port_pubkey")
        self.gridLayout_2.addWidget(self.in_device_port_pubkey, 37, 0, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_16.setObjectName("label_16")
        self.gridLayout_2.addWidget(self.label_16, 7, 0, 1, 1)
        self.out_count_status = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents_2)
        self.out_count_status.setMinimumSize(QtCore.QSize(0, 32))
        self.out_count_status.setMaximumSize(QtCore.QSize(16777215, 32))
        self.out_count_status.setStyleSheet("background-color: rgb(233, 233, 233);")
        self.out_count_status.setObjectName("out_count_status")
        self.gridLayout_2.addWidget(self.out_count_status, 10, 0, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_22.setObjectName("label_22")
        self.gridLayout_2.addWidget(self.label_22, 11, 0, 1, 1)
        self.out_sign_status = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents_2)
        self.out_sign_status.setMinimumSize(QtCore.QSize(0, 32))
        self.out_sign_status.setMaximumSize(QtCore.QSize(16777215, 32))
        self.out_sign_status.setStyleSheet("background-color: rgb(233, 233, 233);")
        self.out_sign_status.setObjectName("out_sign_status")
        self.gridLayout_2.addWidget(self.out_sign_status, 8, 0, 1, 1)
        self.out_date_time_status = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents_2)
        self.out_date_time_status.setMinimumSize(QtCore.QSize(0, 32))
        self.out_date_time_status.setMaximumSize(QtCore.QSize(16777215, 32))
        self.out_date_time_status.setStyleSheet("background-color: rgb(233, 233, 233);")
        self.out_date_time_status.setObjectName("out_date_time_status")
        self.gridLayout_2.addWidget(self.out_date_time_status, 12, 0, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_23.setObjectName("label_23")
        self.gridLayout_2.addWidget(self.label_23, 19, 9, 1, 1)
        self.out_prev_counter = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents_2)
        self.out_prev_counter.setMinimumSize(QtCore.QSize(0, 32))
        self.out_prev_counter.setMaximumSize(QtCore.QSize(16777215, 32))
        self.out_prev_counter.setStyleSheet("background-color: rgb(233, 233, 233);")
        self.out_prev_counter.setObjectName("out_prev_counter")
        self.gridLayout_2.addWidget(self.out_prev_counter, 19, 10, 1, 1)
        self.out_save_name = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents_2)
        self.out_save_name.setMinimumSize(QtCore.QSize(0, 32))
        self.out_save_name.setMaximumSize(QtCore.QSize(16777215, 32))
        self.out_save_name.setStyleSheet("background-color: rgb(233, 233, 233);")
        self.out_save_name.setObjectName("out_save_name")
        self.gridLayout_2.addWidget(self.out_save_name, 6, 9, 1, 2)
        self.label_24 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_24.setObjectName("label_24")
        self.gridLayout_2.addWidget(self.label_24, 16, 7, 1, 1)
        self.out_sender_name = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        self.out_sender_name.setStyleSheet("background-color: rgb(233, 233, 233);")
        self.out_sender_name.setObjectName("out_sender_name")
        self.gridLayout_2.addWidget(self.out_sender_name, 16, 8, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 16, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_2)
        self.gridLayout.addWidget(self.scrollArea, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1078, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_12.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">ECDSA Information:</span></p></body></html>"))
        self.pB_save_pub_key.setText(_translate("MainWindow", "save key"))
        self.label_7.setText(_translate("MainWindow", "public key:"))
        self.label_9.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">ATECC508A Configuration:</span></p></body></html>"))
        self.label_15.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Device Setttings:</span></p></body></html>"))
        self.pB_start_auto.setText(_translate("MainWindow", "Start Automatic Programm"))
        self.label_14.setText(_translate("MainWindow", "device IP:"))
        self.label_13.setText(_translate("MainWindow", "device Port pictures:"))
        self.label_10.setText(_translate("MainWindow", "config zone:"))
        self.label_11.setText(_translate("MainWindow", "data zone:"))
        self.label_4.setText(_translate("MainWindow", "date:"))
        self.label_5.setText(_translate("MainWindow", "time:"))
        self.display.setText(_translate("MainWindow", "TextLabel"))
        self.pB_save_current_pic.setText(_translate("MainWindow", "save current picture"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\">saved as: </p></body></html>"))
        self.label_20.setText(_translate("MainWindow", "device Port public key:"))
        self.logo.setText(_translate("MainWindow", "TextLabel"))
        self.label_19.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Pictures Metadata:</span></p></body></html>"))
        self.label_18.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Simulation Tools:</span></p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "signature:"))
        self.label_2.setText(_translate("MainWindow", "hash value:"))
        self.label_sensor_4.setText(_translate("MainWindow", "sensor 4:"))
        self.label_sensor_3.setText(_translate("MainWindow", "sensor 3:"))
        self.label_6.setText(_translate("MainWindow", "current counter:"))
        self.label_sensor_1.setText(_translate("MainWindow", "sensor 1:"))
        self.label_sensor_2.setText(_translate("MainWindow", "sensor 2:"))
        self.label_21.setText(_translate("MainWindow", "counter status:"))
        self.label_17.setText(_translate("MainWindow", "current date-time:"))
        self.label_16.setText(_translate("MainWindow", "signature status:"))
        self.label_22.setText(_translate("MainWindow", "date-time status:"))
        self.label_23.setText(_translate("MainWindow", "prev. counter:"))
        self.label_24.setText(_translate("MainWindow", "sender name:"))
        self.label_8.setText(_translate("MainWindow", "serial number:"))

