# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Sender.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1249, 1145)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(13, 13, 13, 13)
        self.gridLayout.setSpacing(9)
        self.gridLayout.setObjectName("gridLayout")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, -582, 1314, 1612))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_2)
        self.gridLayout_2.setContentsMargins(13, 13, 13, 13)
        self.gridLayout_2.setSpacing(9)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.widget = QtWidgets.QWidget(self.scrollAreaWidgetContents_2)
        self.widget.setObjectName("widget")
        self.gridLayout_2.addWidget(self.widget, 18, 6, 1, 1)
        self.in_man_date = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        self.in_man_date.setMinimumSize(QtCore.QSize(250, 30))
        self.in_man_date.setObjectName("in_man_date")
        self.gridLayout_2.addWidget(self.in_man_date, 13, 8, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(100, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 13, 6, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 13, 9, 1, 1)
        self.pB_load_new_pic = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.pB_load_new_pic.setObjectName("pB_load_new_pic")
        self.gridLayout_2.addWidget(self.pB_load_new_pic, 4, 7, 1, 1)
        self.logo = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.logo.setMinimumSize(QtCore.QSize(318, 303))
        self.logo.setMaximumSize(QtCore.QSize(1000000, 10000000))
        self.logo.setObjectName("logo")
        self.gridLayout_2.addWidget(self.logo, 0, 0, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_19.setObjectName("label_19")
        self.gridLayout_2.addWidget(self.label_19, 9, 7, 2, 2)
        self.out_signature = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents_2)
        self.out_signature.setMinimumSize(QtCore.QSize(0, 124))
        self.out_signature.setStyleSheet("background-color: rgb(233, 233, 233);")
        self.out_signature.setObjectName("out_signature")
        self.gridLayout_2.addWidget(self.out_signature, 31, 8, 4, 3)
        self.in_dest_port_pubkey = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        self.in_dest_port_pubkey.setMinimumSize(QtCore.QSize(0, 32))
        self.in_dest_port_pubkey.setObjectName("in_dest_port_pubkey")
        self.gridLayout_2.addWidget(self.in_dest_port_pubkey, 33, 0, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_16.setObjectName("label_16")
        self.gridLayout_2.addWidget(self.label_16, 15, 7, 1, 1)
        self.out_public_key = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents_2)
        self.out_public_key.setMinimumSize(QtCore.QSize(0, 124))
        self.out_public_key.setStyleSheet("background-color: rgb(233, 233, 233);")
        self.out_public_key.setObjectName("out_public_key")
        self.gridLayout_2.addWidget(self.out_public_key, 35, 8, 4, 3)
        self.label_4 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 13, 7, 1, 1)
        self.out_conf_zone = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents_2)
        self.out_conf_zone.setMinimumSize(QtCore.QSize(0, 32))
        self.out_conf_zone.setMaximumSize(QtCore.QSize(16777215, 32))
        self.out_conf_zone.setStyleSheet("background-color: rgb(233, 233, 233);")
        self.out_conf_zone.setObjectName("out_conf_zone")
        self.gridLayout_2.addWidget(self.out_conf_zone, 15, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 40, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 8, 0, 1, 1)
        self.display = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.display.setMinimumSize(QtCore.QSize(721, 521))
        self.display.setMaximumSize(QtCore.QSize(1500, 700))
        self.display.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.display.setLineWidth(3)
        self.display.setMidLineWidth(3)
        self.display.setObjectName("display")
        self.gridLayout_2.addWidget(self.display, 0, 7, 3, 7)
        self.in_sensor_2 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        self.in_sensor_2.setMinimumSize(QtCore.QSize(250, 30))
        self.in_sensor_2.setObjectName("in_sensor_2")
        self.gridLayout_2.addWidget(self.in_sensor_2, 18, 10, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_20.setObjectName("label_20")
        self.gridLayout_2.addWidget(self.label_20, 32, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 4, 8, 1, 1)
        self.out_hash_value = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents_2)
        self.out_hash_value.setMinimumSize(QtCore.QSize(0, 124))
        self.out_hash_value.setStyleSheet("background-color: rgb(233, 233, 233);")
        self.out_hash_value.setObjectName("out_hash_value")
        self.gridLayout_2.addWidget(self.out_hash_value, 27, 8, 4, 3)
        self.in_sensor_3 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        self.in_sensor_3.setMinimumSize(QtCore.QSize(250, 30))
        self.in_sensor_3.setObjectName("in_sensor_3")
        self.gridLayout_2.addWidget(self.in_sensor_3, 20, 8, 1, 1)
        self.in_counter = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        self.in_counter.setMinimumSize(QtCore.QSize(250, 30))
        self.in_counter.setObjectName("in_counter")
        self.gridLayout_2.addWidget(self.in_counter, 16, 8, 1, 1)
        self.in_sensor_1 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        self.in_sensor_1.setMinimumSize(QtCore.QSize(250, 30))
        self.in_sensor_1.setObjectName("in_sensor_1")
        self.gridLayout_2.addWidget(self.in_sensor_1, 18, 8, 2, 1)
        self.label_sensor_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_sensor_2.setObjectName("label_sensor_2")
        self.gridLayout_2.addWidget(self.label_sensor_2, 18, 9, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 27, 7, 1, 1)
        self.label_sensor_4 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_sensor_4.setObjectName("label_sensor_4")
        self.gridLayout_2.addWidget(self.label_sensor_4, 20, 9, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_18.setObjectName("label_18")
        self.gridLayout_2.addWidget(self.label_18, 2, 0, 1, 1)
        self.out_file_name = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents_2)
        self.out_file_name.setMinimumSize(QtCore.QSize(250, 30))
        self.out_file_name.setMaximumSize(QtCore.QSize(16777215, 30))
        self.out_file_name.setObjectName("out_file_name")
        self.gridLayout_2.addWidget(self.out_file_name, 4, 9, 1, 5)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 24, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 50, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem3, 23, 7, 3, 3)
        self.label_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 31, 7, 1, 1)
        self.in_sensor_4 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        self.in_sensor_4.setMinimumSize(QtCore.QSize(250, 30))
        self.in_sensor_4.setObjectName("in_sensor_4")
        self.gridLayout_2.addWidget(self.in_sensor_4, 20, 10, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 16, 7, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_17.setObjectName("label_17")
        self.gridLayout_2.addWidget(self.label_17, 14, 7, 1, 1)
        self.in_dest_port_pic = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        self.in_dest_port_pic.setMinimumSize(QtCore.QSize(0, 32))
        self.in_dest_port_pic.setObjectName("in_dest_port_pic")
        self.gridLayout_2.addWidget(self.in_dest_port_pic, 31, 0, 1, 1)
        self.label_sensor_1 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_sensor_1.setObjectName("label_sensor_1")
        self.gridLayout_2.addWidget(self.label_sensor_1, 18, 7, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_12.setObjectName("label_12")
        self.gridLayout_2.addWidget(self.label_12, 20, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_13.setObjectName("label_13")
        self.gridLayout_2.addWidget(self.label_13, 30, 0, 1, 1)
        self.pB_send_valid = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.pB_send_valid.setObjectName("pB_send_valid")
        self.gridLayout_2.addWidget(self.pB_send_valid, 7, 0, 1, 1)
        self.out_current_date_time = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents_2)
        self.out_current_date_time.setMinimumSize(QtCore.QSize(250, 32))
        self.out_current_date_time.setMaximumSize(QtCore.QSize(16777215, 30))
        self.out_current_date_time.setStyleSheet("background-color: rgb(233, 233, 233);")
        self.out_current_date_time.setObjectName("out_current_date_time")
        self.gridLayout_2.addWidget(self.out_current_date_time, 14, 8, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_14.setObjectName("label_14")
        self.gridLayout_2.addWidget(self.label_14, 28, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 10, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 9, 0, 1, 1)
        self.pB_send_invalid_2 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.pB_send_invalid_2.setObjectName("pB_send_invalid_2")
        self.gridLayout_2.addWidget(self.pB_send_invalid_2, 6, 0, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_15.setObjectName("label_15")
        self.gridLayout_2.addWidget(self.label_15, 27, 0, 1, 1)
        self.cB_use_current_time = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_2)
        self.cB_use_current_time.setText("")
        self.cB_use_current_time.setObjectName("cB_use_current_time")
        self.gridLayout_2.addWidget(self.cB_use_current_time, 15, 8, 1, 1)
        self.pB_send_valid_2 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.pB_send_valid_2.setObjectName("pB_send_valid_2")
        self.gridLayout_2.addWidget(self.pB_send_valid_2, 4, 0, 1, 1)
        self.pB_send_pub_key = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.pB_send_pub_key.setObjectName("pB_send_pub_key")
        self.gridLayout_2.addWidget(self.pB_send_pub_key, 37, 7, 1, 1)
        self.out_data_zone = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents_2)
        self.out_data_zone.setMinimumSize(QtCore.QSize(0, 32))
        self.out_data_zone.setMaximumSize(QtCore.QSize(16777215, 30))
        self.out_data_zone.setStyleSheet("background-color: rgb(233, 233, 233);")
        self.out_data_zone.setObjectName("out_data_zone")
        self.gridLayout_2.addWidget(self.out_data_zone, 18, 0, 1, 1)
        self.pB_send_invalid = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.pB_send_invalid.setObjectName("pB_send_invalid")
        self.gridLayout_2.addWidget(self.pB_send_invalid, 5, 0, 1, 1)
        self.label_sensor_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_sensor_3.setObjectName("label_sensor_3")
        self.gridLayout_2.addWidget(self.label_sensor_3, 20, 7, 1, 1)
        self.pB_gen_new_key = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.pB_gen_new_key.setObjectName("pB_gen_new_key")
        self.gridLayout_2.addWidget(self.pB_gen_new_key, 38, 7, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 16, 0, 1, 1)
        self.in_man_time = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        self.in_man_time.setMinimumSize(QtCore.QSize(250, 30))
        self.in_man_time.setObjectName("in_man_time")
        self.gridLayout_2.addWidget(self.in_man_time, 13, 10, 1, 1)
        self.out_key_slot = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents_2)
        self.out_key_slot.setMinimumSize(QtCore.QSize(0, 32))
        self.out_key_slot.setMaximumSize(QtCore.QSize(16777215, 30))
        self.out_key_slot.setStyleSheet("background-color: rgb(233, 233, 233);")
        self.out_key_slot.setObjectName("out_key_slot")
        self.gridLayout_2.addWidget(self.out_key_slot, 21, 0, 1, 1)
        self.out_serial_number = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents_2)
        self.out_serial_number.setMinimumSize(QtCore.QSize(0, 32))
        self.out_serial_number.setMaximumSize(QtCore.QSize(16777215, 32))
        self.out_serial_number.setStyleSheet("background-color: rgb(233, 233, 233);")
        self.out_serial_number.setObjectName("out_serial_number")
        self.gridLayout_2.addWidget(self.out_serial_number, 13, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 14, 0, 1, 1)
        self.in_dest_ip = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        self.in_dest_ip.setMinimumSize(QtCore.QSize(0, 32))
        self.in_dest_ip.setObjectName("in_dest_ip")
        self.gridLayout_2.addWidget(self.in_dest_ip, 29, 0, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_21.setObjectName("label_21")
        self.gridLayout_2.addWidget(self.label_21, 26, 7, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 35, 7, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_2)
        self.gridLayout.addWidget(self.scrollArea, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1249, 31))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_5.setText(_translate("MainWindow", "time:"))
        self.pB_load_new_pic.setText(_translate("MainWindow", "load new picture"))
        self.logo.setText(_translate("MainWindow", "TextLabel"))
        self.label_19.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Pictures Metadata:</span></p></body></html>"))
        self.label_16.setText(_translate("MainWindow", "use current date and time"))
        self.label_4.setText(_translate("MainWindow", "date:"))
        self.display.setText(_translate("MainWindow", "TextLabel"))
        self.label_20.setText(_translate("MainWindow", "dest. Port public key:"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\">file name:</p></body></html>"))
        self.label_sensor_2.setText(_translate("MainWindow", "sensor 2:"))
        self.label_2.setText(_translate("MainWindow", "hash value:"))
        self.label_sensor_4.setText(_translate("MainWindow", "sensor 4:"))
        self.label_18.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Simulation Tools:</span></p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "signature:"))
        self.label_6.setText(_translate("MainWindow", "counter:"))
        self.label_17.setText(_translate("MainWindow", "current date-time:"))
        self.label_sensor_1.setText(_translate("MainWindow", "sensor 1:"))
        self.label_12.setText(_translate("MainWindow", "active Key-Slot:"))
        self.label_13.setText(_translate("MainWindow", "dest. Port pictures:"))
        self.pB_send_valid.setText(_translate("MainWindow", "Send Picture With Valid Signature"))
        self.label_14.setText(_translate("MainWindow", "dest. IP:"))
        self.label_8.setText(_translate("MainWindow", "serial number:"))
        self.label_9.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">ATECC508A Configuration:</span></p></body></html>"))
        self.pB_send_invalid_2.setText(_translate("MainWindow", "Send Picture With Privious Signature"))
        self.label_15.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Destination Setttings:</span></p></body></html>"))
        self.pB_send_valid_2.setText(_translate("MainWindow", "Start Automatic Programm"))
        self.pB_send_pub_key.setText(_translate("MainWindow", "send key"))
        self.pB_send_invalid.setText(_translate("MainWindow", "Send Picture With Invalid Signature"))
        self.label_sensor_3.setText(_translate("MainWindow", "sensor 3:"))
        self.pB_gen_new_key.setText(_translate("MainWindow", "generate new key"))
        self.label_11.setText(_translate("MainWindow", "data zone:"))
        self.label_10.setText(_translate("MainWindow", "config zone:"))
        self.label_21.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">ECDSA Inforamtion</span></p></body></html>"))
        self.label_7.setText(_translate("MainWindow", "public key:"))

